import AppKit
import CryptoKit
import Foundation

struct PasteboardSnapshot {
    let changeCount: Int
    let sourceBundleID: String?
    let types: [String]
    let dataByType: [String: Data]
}

struct CapturedPayload {
    let kind: ClipboardItemKind
    let text: String?
    let preview: String
    let contentHash: String
    let byteSize: Int
    let representations: [(type: String, data: Data)]
    let displayPNG: Data?
    let thumbnailPNG: Data?
}

enum PasteboardCapture {
    static let maxImageBytes = 20 * 1024 * 1024
    static let maxTextBytes = 1_000_000
    static let maxOtherBytes = 8 * 1024 * 1024
    static let maxImageDimension: CGFloat = 4096

    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private static let keptTypes: Set<String> = [
        NSPasteboard.PasteboardType.string.rawValue,
        NSPasteboard.PasteboardType.rtf.rawValue,
        NSPasteboard.PasteboardType.html.rawValue,
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue,
        NSPasteboard.PasteboardType.fileURL.rawValue,
        NSPasteboard.PasteboardType.URL.rawValue,
        "public.utf8-plain-text",
        "public.utf16-plain-text",
        "public.rtf",
        "public.html",
        "public.png",
        "public.tiff",
        "public.jpeg",
        "public.file-url",
        "public.url",
        "Apple HTML pasteboard type",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "NSStringPboardType"
    ]

    private static let imageTypes: Set<String> = [
        NSPasteboard.PasteboardType.png.rawValue,
        NSPasteboard.PasteboardType.tiff.rawValue,
        "public.png",
        "public.tiff",
        "public.jpeg"
    ]

    static func snapshot(
        _ pasteboard: NSPasteboard = .general,
        sourceBundleID: String?
    ) -> PasteboardSnapshot? {
        let types = (pasteboard.types ?? []).map(\.rawValue)
        if types.contains(where: { skippedTypes.contains($0) }) {
            return nil
        }

        var dataByType: [String: Data] = [:]
        for raw in types where keptTypes.contains(raw) {
            let type = NSPasteboard.PasteboardType(raw)
            guard let data = pasteboard.data(forType: type), !data.isEmpty else { continue }
            let limit = imageTypes.contains(raw) ? maxImageBytes : (isTextType(raw) ? maxTextBytes : maxOtherBytes)
            guard data.count <= limit else { continue }
            dataByType[raw] = data
        }

        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue),
           dataByType[NSPasteboard.PasteboardType.fileURL.rawValue] == nil,
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !urls.isEmpty {
            let joined = urls.map(\.absoluteString).joined(separator: "\n")
            if let data = joined.data(using: .utf8) {
                dataByType[NSPasteboard.PasteboardType.fileURL.rawValue] = data
            }
        }

        if dataByType[NSPasteboard.PasteboardType.string.rawValue] == nil,
           let text = pasteboard.string(forType: .string),
           !text.isEmpty,
           let data = clampText(text).data(using: .utf8) {
            dataByType[NSPasteboard.PasteboardType.string.rawValue] = data
        }

        guard !dataByType.isEmpty else { return nil }

        return PasteboardSnapshot(
            changeCount: pasteboard.changeCount,
            sourceBundleID: sourceBundleID,
            types: types,
            dataByType: dataByType
        )
    }

    static func process(_ snapshot: PasteboardSnapshot) -> CapturedPayload? {
        let dataByType = snapshot.dataByType
        guard !dataByType.isEmpty else { return nil }

        let text = plainText(from: dataByType)
        let hasRTF = dataByType.keys.contains(where: { $0.contains("rtf") || $0 == NSPasteboard.PasteboardType.rtf.rawValue })
        let hasHTML = dataByType.keys.contains(where: { $0.contains("html") })
        let hasImage = dataByType.keys.contains(where: { imageTypes.contains($0) })
        let hasFiles = dataByType[NSPasteboard.PasteboardType.fileURL.rawValue] != nil

        let kind: ClipboardItemKind
        if hasImage && (text == nil || text?.isEmpty == true) {
            kind = .image
        } else if hasFiles && !hasRTF && !hasHTML && !hasImage {
            kind = .files
        } else if hasRTF || hasHTML {
            kind = .richText
        } else if hasImage {
            kind = .image
        } else {
            kind = .text
        }

        if kind == .text {
            guard let text, !text.isEmpty else {
                if !hasImage && !hasFiles { return nil }
                return processImageOrFiles(dataByType: dataByType, kind: hasImage ? .image : .files, text: text)
            }
        }

        var displayPNG: Data?
        var thumbPNG: Data?
        if hasImage, let imageData = preferredImageData(from: dataByType) {
            if let image = NSImage(data: imageData) {
                displayPNG = pngData(from: image)
                thumbPNG = makeThumbnailPNG(from: image)
            }
        }

        let representations = dataByType
            .map { ($0.key, $0.value) }
            .sorted { $0.0 < $1.0 }

        let hash = contentHash(kind: kind, text: text, dataByType: dataByType)
        let preview: String
        switch kind {
        case .image:
            preview = "Imagen"
        case .files:
            preview = filePreview(from: dataByType, fallback: text)
        case .text, .richText:
            preview = (text?.isEmpty == false) ? makePreview(from: text!) : kind.label
        }

        let byteSize = dataByType.values.reduce(0) { $0 + $1.count }

        return CapturedPayload(
            kind: kind,
            text: text,
            preview: preview,
            contentHash: hash,
            byteSize: byteSize,
            representations: representations,
            displayPNG: displayPNG,
            thumbnailPNG: thumbPNG
        )
    }

    private static func processImageOrFiles(
        dataByType: [String: Data],
        kind: ClipboardItemKind,
        text: String?
    ) -> CapturedPayload? {
        var displayPNG: Data?
        var thumbPNG: Data?
        if kind == .image, let imageData = preferredImageData(from: dataByType), let image = NSImage(data: imageData) {
            displayPNG = pngData(from: image)
            thumbPNG = makeThumbnailPNG(from: image)
        }
        let representations = dataByType.map { ($0.key, $0.value) }.sorted { $0.0 < $1.0 }
        guard !representations.isEmpty else { return nil }
        return CapturedPayload(
            kind: kind,
            text: text,
            preview: kind == .image ? "Imagen" : filePreview(from: dataByType, fallback: text),
            contentHash: contentHash(kind: kind, text: text, dataByType: dataByType),
            byteSize: dataByType.values.reduce(0) { $0 + $1.count },
            representations: representations,
            displayPNG: displayPNG,
            thumbnailPNG: thumbPNG
        )
    }

    private static func plainText(from dataByType: [String: Data]) -> String? {
        let keys = [
            NSPasteboard.PasteboardType.string.rawValue,
            "public.utf8-plain-text",
            "NSStringPboardType"
        ]
        for key in keys {
            if let data = dataByType[key], let text = String(data: data, encoding: .utf8) {
                let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
                if !trimmed.isEmpty { return clampText(trimmed) }
            }
        }
        if let data = dataByType["public.utf16-plain-text"],
           let text = String(data: data, encoding: .utf16) {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { return clampText(trimmed) }
        }
        if let data = dataByType[NSPasteboard.PasteboardType.fileURL.rawValue],
           let text = String(data: data, encoding: .utf8) {
            let paths = text
                .split(whereSeparator: \.isNewline)
                .compactMap { URL(string: String($0)).map { $0.path.isEmpty ? $0.absoluteString : $0.path } }
            if !paths.isEmpty {
                return clampText(paths.joined(separator: "\n"))
            }
        }
        return nil
    }

    private static func preferredImageData(from dataByType: [String: Data]) -> Data? {
        let keys = [
            NSPasteboard.PasteboardType.png.rawValue,
            "public.png",
            "public.jpeg",
            NSPasteboard.PasteboardType.tiff.rawValue,
            "public.tiff"
        ]
        for key in keys {
            if let data = dataByType[key], data.count > 32 { return data }
        }
        return nil
    }

    private static func filePreview(from dataByType: [String: Data], fallback: String?) -> String {
        if let text = fallback, !text.isEmpty {
            let first = text.split(whereSeparator: \.isNewline).first.map(String.init) ?? text
            return makePreview(from: (first as NSString).lastPathComponent)
        }
        if let data = dataByType[NSPasteboard.PasteboardType.fileURL.rawValue],
           let raw = String(data: data, encoding: .utf8),
           let url = URL(string: raw.split(whereSeparator: \.isNewline).first.map(String.init) ?? raw) {
            return url.lastPathComponent.isEmpty ? "Archivos" : url.lastPathComponent
        }
        return "Archivos"
    }

    private static func contentHash(kind: ClipboardItemKind, text: String?, dataByType: [String: Data]) -> String {
        if let text, (kind == .text || kind == .richText || kind == .files) {
            return sha256(Data(text.utf8))
        }
        if let image = preferredImageData(from: dataByType) {
            return sha256(image)
        }
        var hasher = SHA256()
        for key in dataByType.keys.sorted() {
            hasher.update(data: Data(key.utf8))
            if let data = dataByType[key] {
                hasher.update(data: data)
            }
        }
        return hasher.finalize().compactMap { String(format: "%02x", $0) }.joined()
    }

    private static func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).compactMap { String(format: "%02x", $0) }.joined()
    }

    static func makePreview(from text: String, limit: Int = 240) -> String {
        let collapsed = text
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if collapsed.count <= limit { return collapsed }
        let end = collapsed.index(collapsed.startIndex, offsetBy: limit)
        return String(collapsed[..<end]) + "…"
    }

    static func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }

        let width = CGFloat(rep.pixelsWide)
        let height = CGFloat(rep.pixelsHigh)
        let longest = max(width, height)

        let finalRep: NSBitmapImageRep
        if longest > maxImageDimension, width > 0, height > 0 {
            let scale = maxImageDimension / longest
            let newSize = NSSize(width: floor(width * scale), height: floor(height * scale))
            guard let resized = resize(rep, to: newSize) else { return nil }
            finalRep = resized
        } else {
            finalRep = rep
        }

        return finalRep.representation(using: .png, properties: [:])
    }

    static func makeThumbnailPNG(from image: NSImage, maxDimension: CGFloat = 160) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        let width = CGFloat(rep.pixelsWide)
        let height = CGFloat(rep.pixelsHigh)
        let longest = max(width, height)
        guard longest > 0 else { return nil }
        let scale = min(1, maxDimension / longest)
        let newSize = NSSize(width: max(1, floor(width * scale)), height: max(1, floor(height * scale)))
        guard let resized = resize(rep, to: newSize) else { return nil }
        return resized.representation(using: .png, properties: [:])
    }

    private static func resize(_ rep: NSBitmapImageRep, to size: NSSize) -> NSBitmapImageRep? {
        guard let resized = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: Int(size.width),
            pixelsHigh: Int(size.height),
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: resized)
        NSGraphicsContext.current?.imageInterpolation = .high
        rep.draw(in: NSRect(origin: .zero, size: size))
        NSGraphicsContext.restoreGraphicsState()
        return resized
    }

    private static func isTextType(_ raw: String) -> Bool {
        raw.contains("text") || raw.contains("rtf") || raw.contains("html") || raw == "NSStringPboardType"
    }

    private static func clampText(_ text: String) -> String {
        if text.utf8.count <= maxTextBytes { return text }
        var result = text
        while result.utf8.count > maxTextBytes {
            let idx = result.index(result.endIndex, offsetBy: -256, limitedBy: result.startIndex) ?? result.startIndex
            result = String(result[..<idx])
        }
        return result
    }
}
