import AppKit
import CryptoKit
import Foundation

enum CapturedContent {
    case text(String)
    case image(NSImage, pngData: Data)

    var contentHash: String {
        switch self {
        case .text(let text):
            return SHA256.hash(data: Data(text.utf8)).compactMap { String(format: "%02x", $0) }.joined()
        case .image(_, let data):
            return SHA256.hash(data: data).compactMap { String(format: "%02x", $0) }.joined()
        }
    }

    var preview: String {
        switch self {
        case .text(let text):
            return Self.makePreview(from: text)
        case .image:
            return "Imagen"
        }
    }

    var byteSize: Int {
        switch self {
        case .text(let text):
            return text.utf8.count
        case .image(_, let data):
            return data.count
        }
    }

    static func makePreview(from text: String, limit: Int = 240) -> String {
        let collapsed = text
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        if collapsed.count <= limit { return collapsed }
        let end = collapsed.index(collapsed.startIndex, offsetBy: limit)
        return String(collapsed[..<end]) + "…"
    }
}

enum PasteboardCapture {
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    static let maxImageBytes = 20 * 1024 * 1024
    static let maxTextBytes = 1_000_000
    static let maxImageDimension: CGFloat = 4096

    static func capture(_ pasteboard: NSPasteboard = .general) -> CapturedContent? {
        let types = pasteboard.types ?? []
        if types.contains(where: { skippedTypes.contains($0.rawValue) }) {
            return nil
        }

        if containsImage(types), let imageContent = readImage(from: pasteboard) {
            return imageContent
        }

        if let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines),
           !text.isEmpty {
            return .text(clampText(text))
        }

        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path).joined(separator: "\n")
            return .text(clampText(paths))
        }

        return nil
    }

    private static func containsImage(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains(.png) || types.contains(.tiff) || types.contains(NSPasteboard.PasteboardType("public.jpeg"))
    }

    private static func readImage(from pasteboard: NSPasteboard) -> CapturedContent? {
        guard let image = NSImage(pasteboard: pasteboard) else { return nil }
        guard let png = pngData(from: image), png.count <= maxImageBytes, png.count > 32 else {
            return nil
        }
        return .image(image, pngData: png)
    }

    static func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }

        let width = CGFloat(rep.pixelsWide)
        let height = CGFloat(rep.pixelsHigh)
        let longest = max(width, height)

        let finalRep: NSBitmapImageRep
        if longest > maxImageDimension, width > 0, height > 0 {
            let scale = maxImageDimension / longest
            let newSize = NSSize(width: floor(width * scale), height: floor(height * scale))
            guard let resized = resize(rep, to: newSize) else { return nil }
            finalRep = resized
        } else {
            finalRep = rep
        }

        return finalRep.representation(using: .png, properties: [:])
    }

    static func thumbnailPNG(from image: NSImage, maxDimension: CGFloat = 160) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        let width = CGFloat(rep.pixelsWide)
        let height = CGFloat(rep.pixelsHigh)
        let longest = max(width, height)
        guard longest > 0 else { return nil }
        let scale = min(1, maxDimension / longest)
        let newSize = NSSize(width: max(1, floor(width * scale)), height: max(1, floor(height * scale)))
        guard let resized = resize(rep, to: newSize) else { return nil }
        return resized.representation(using: .png, properties: [:])
    }

    private static func resize(_ rep: NSBitmapImageRep, to size: NSSize) -> NSBitmapImageRep? {
        guard let resized = NSBitmapImageRep(
            bitmapDataPlanes: nil,
            pixelsWide: Int(size.width),
            pixelsHigh: Int(size.height),
            bitsPerSample: 8,
            samplesPerPixel: 4,
            hasAlpha: true,
            isPlanar: false,
            colorSpaceName: .deviceRGB,
            bytesPerRow: 0,
            bitsPerPixel: 0
        ) else { return nil }

        NSGraphicsContext.saveGraphicsState()
        NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: resized)
        NSGraphicsContext.current?.imageInterpolation = .high
        rep.draw(in: NSRect(origin: .zero, size: size))
        NSGraphicsContext.restoreGraphicsState()
        return resized
    }

    private static func clampText(_ text: String) -> String {
        if text.utf8.count <= maxTextBytes { return text }
        var result = text
        while result.utf8.count > maxTextBytes {
            let idx = result.index(result.endIndex, offsetBy: -256, limitedBy: result.startIndex) ?? result.startIndex
            result = String(result[..<idx])
        }
        return result
    }
}
